[package]
name = "util-rs"
version = "0.1.0"
authors = ["Trung Tran <tqtrungse@gmail.com>"]
edition = "2021"
description = "Utililites for omango library"
license = "MIT"
repository = "https://github.com/tqtrungse/util-rs"
homepage = "https://github.com/tqtrungse/util-rs"
documentation = "https://docs.rs/util-rs"
keywords = ["cpu-cacheline", "backoff", "hint"]
categories = ["data-structures"]

